### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by Kobzol** [seznam/IMA.js-skeleton#5]
Could you please check whether the build is working after the latest merge?
I'm not able to complete npm install, it fails to build (first it couldn't find proper MSbuild files, after I told npm to use VS12, it failed to compile V8 C++ files).

**Comment by mjancarik** [comment]
The installation for Mac and Linux works properly. The installation is harder on Windows, because external library needs VS compiler.
I think that problem may be with [https://github.com/nodejs/node-gyp]. Check installation section.

We will try it too, but we need more details about your operating system, node version and npm version. 

Commands:

```
npm -v
node -v
```

**Comment by Kobzol** [comment]
I reinstalled npm and node to the newest version, but the problem probably lies with node-gyp, as you wrote. Their installation info didn't help though, I wasn't able to install the Windows 64-bit SDK and I don't want to uninstall all C++ redistributables for it to work, so I'll just leave it aside for now. Thanks for your help :-)

**Comment by mjancarik** [comment]
We successfully twice install IMA.js on Windows 7. Module https://github.com/nodejs/node-gyp showed error on the terminal but it didn't affect installation. 

We removed karma launchers. You will try update package version the ima.js-gulp-tasks to 0.10.13.

**Comment by Kobzol** [comment]
It fails with this error:

C:\Users\Jakub\Desktop\Programovani\js\ima\ima-skeleton\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Users\Jakub\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node  rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
**C:\Users\Jakub\Desktop\Programovani\js\ima\ima-skeleton\node_modules\fibers\build\fibers.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.**
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Jakub\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Jakub\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\Jakub\Desktop\Programovani\js\ima\ima-skeleton\node_modules\fibers
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.2.0
gyp ERR! not ok
Build failed
'nodejs' is not recognized as an internal or external command,
operable program or batch file.

It seems that it has a problem with my VS setup. I tried installing both with VS12 and VS13 (npm install --msvs_version=2012/2013), but neither worked.

**Comment by mjancarik** [comment]
I will try it again on Windows.

**Comment by mjancarik** [comment]
I have successfully installed IMA.js v0.10.0 on fresh Windows, where weren't Virtual Studio, Python and Git. I have only installed git for Windows and node v5.2.0 . Then I continued with steps https://github.com/seznam/IMA.js-skeleton#installation.

I publish only for your test purposes ima.js-gulp-tasks v0.1.0, where I removed fibers from dependencies. You can try it.

**Comment by Kobzol** [comment]
I used the LTS x64 version of Node.js before (4.3.x), now I tried it with the newest x86 version (5.2.x).
There were some errors during the installation, but it finally finished the build and it works now :-) Thank you for your help :-)

**Comment by mjancarik** [comment]
Happy ending story :-)
