### ISSUE TITLE
IMA not building

### ISSUE THREAD

**Issue by anthonybrown** [seznam/IMA.js-skeleton#6]
Here is my [npm-error-log](https://gist.github.com/anthonybrown/e2108d14870f5636fc26132dd932ce5b)

Seems like it can't find the fibers-1.0.11.tgz package

**Comment by anthonybrown** [comment]
I got it running by installing gulp `npm --save-dev i gulp` 
Gulp is installed globally on my machine but for some reason I have to install it locally. Running `npm app:hello` doesn't work, I just did `npm start` which started the local server on port 3001.

**Comment by mjancarik** [comment]
Hi Anthony,

Can you send me more information about os, node version and npm version? I will try it for your sent configuration.

The task npm run app:hello creating app folder and the gulp has to installed always locally.

**Comment by anthonybrown** [comment]
@mjancarik sorry for the delay, 
Here is [my](http://bit.ly/1TMioHL) enviroment
I'm on osx, latest versions of node, ruby, etc...

**Comment by anthonybrown** [comment]
`/JavaScript_Projects/IMA.js-skeleton                                                                                                [git:master]
 → npm run app:hello

```
IMA.js-skeleton@0.12.1 app:hello /Users/tonybrown/Documents/Development/JavaScript_Projects/IMA.js-skeleton
node node_modules/gulp/bin/gulp.js app:hello

{ Error: Cannot find module './app/build.js'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tonybrown/Documents/Development/JavaScript_Projects/IMA.js-skeleton/gulpConfig.js:6:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3) code: 'MODULE_NOT_FOUND' }
Loading gulp tasks...
(node:86152) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
The gulp tasks directory ./app/gulp/tasks does not exist, skipping
[06:58:23] Using gulpfile ~/Documents/Development/JavaScript_Projects/IMA.js-skeleton/gulpfile.js
[06:58:23] Starting 'app:hello'...
[06:58:23] Finished 'app:hello' after 217 ms`
```

**Comment by anthonybrown** [comment]
@mjancarik, what worked for me:
- 1. npm i
- 2. npm run build
- 3. npm run app:hello
- 4. npm start

Those are the steps I had to take to get the server running.

**Comment by mjancarik** [comment]
Hi,

Thank you for more details. I will test it.

The error for task npm run app:hello is catched and only log it, but the instalation application hello world finished all rights. It may be confused I will remove it from other version. The task app:hello is generator similar with http://yeoman.io, but we use gulp task now.

You can try other prepared examples (if you have installed gulp):
`
gulp app:clean // delete app folder
gulp app:feed // install example feed
gulp dev

gulp app:clean // delete app folder
gulp app:todos // install example TODO
gulp dev
`

The tasks npm run build and npm start is for production. For development purpose is better use npm run dev (gulp dev).

Thank you for your feed back.
